   services:
  - type: web
    name: auto-uploader-bot 
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/yassuhacks750/Auto-uploader-bot
    branch: main
    autoDeploy: false
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      #- key: WEBHOOK
        #sync: false
        - key: PORT
        value: 10000
        
    
    
        
